# Generated by Django 5.1 on 2024-08-18 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crc_ONOFF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event_minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('circuit_id', models.PositiveSmallIntegerField(editable=False)),
                ('circuit_event', models.PositiveSmallIntegerField(editable=False)),
                ('slug2', models.SlugField(blank=True, max_length=10, unique=True)),
                ('circuit_mode', models.CharField(max_length=20)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('status1', models.BooleanField(default=False)),
                ('status2', models.BooleanField(default=False)),
                ('status3', models.BooleanField(default=False)),
                ('status4', models.BooleanField(default=False)),
                ('status5', models.BooleanField(default=False)),
                ('status6', models.BooleanField(default=False)),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.crc_prog')),
            ],
        ),
    ]
