# Generated by Django 5.1 on 2024-08-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crc_DES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_id', models.SmallIntegerField()),
                ('circuit_description', models.CharField(max_length=100)),
                ('circuit_status', models.BooleanField(null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('num_cycles', models.SmallIntegerField()),
                ('events_per_cycle', models.SmallIntegerField()),
                ('event_duration', models.SmallIntegerField()),
                ('random', models.BooleanField(default=False)),
                ('circuit_mode', models.CharField(default='PROG', max_length=20)),
            ],
        ),
    ]
