# Generated by Django 5.1 on 2024-08-16 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('descriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='crc_PROG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('event_start_hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event_start_minute', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('circuit_event', models.PositiveSmallIntegerField(null=True)),
                ('event_duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('random', models.BooleanField(default=False)),
                ('circuit_mode', models.CharField(default='PROG', max_length=20)),
                ('circuit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descriptions.crc_des')),
            ],
        ),
    ]
