# Generated by Django 5.1 on 2024-08-17 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descriptions', '0001_initial'),
        ('programs', '0002_alter_crc_prog_circuit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crc_prog',
            name='circuit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='descriptions.crc_des'),
        ),
    ]
